### ISSUE TITLE
Use of `==` in README code

### ISSUE THREAD

**Issue by lindig** [leostera/serde.ml#1]
Code in the README uses at various places `==` which is pointer equality in OCaml and quite likely to be wrong because you are looking for structural equality. Otherwise it would be good to explain why pointer equality is required in these places.

**Comment by leostera** [comment]
Hi @lindig, good call-out. If you look at the tests they're all using `ppx_deriving.eq` to make structural equality comparisons. The readme was illustrative. I'll amend it so its not misleading :) 

Thanks!
